### ISSUE TITLE
An erro with plugin starting....

### ISSUE THREAD

**Issue by SmithJiong** [caoli5288/PlayerSQL#27]
[15:56:55 ERROR]: Error registering MBean[Ebean:server=PlayerSQL2]
java.security.AccessControlException: access denied ("javax.management.MBeanTrus
tPermission" "register")
        at java.security.AccessControlContext.checkPermission(Unknown Source) ~[
?:1.8.0_71]
        at java.lang.SecurityManager.checkPermission(Unknown Source) ~[?:1.8.0_7
1]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrust
Permission(Unknown Source) ~[?:1.8.0_71]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(U
nknown Source) ~[?:1.8.0_71]
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(Unknown Source)
~[?:1.8.0_71]
        at com.avaje.ebeaninternal.server.core.DefaultServer.registerMBeans(Defa
ultServer.java:389) [DefaultServer.class:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer
(DefaultServerFactory.java:226) [DefaultServerFactory.class:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer
(DefaultServerFactory.java:64) [DefaultServerFactory.class:?]
        at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78)
 [EbeanServerFactory.class:?]
        at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:166
) [playersql-2.0-SNAPSHOT.jar:?]
        at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:171
) [playersql-2.0-SNAPSHOT.jar:?]
        at com.mengcraft.playersql.PluginMain.onEnable(PluginMain.java:31) [play
ersql-2.0-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) [Ja
vaPlugin.class:1.7.10-1614.176]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:368) [JavaPluginLoader.class:1.7.10-1614.176]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:410) [SimplePluginManager.class:1.7.10-1614.176]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.jav
a:415) [CraftServer.class:1.7.10-1614.176]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.
java:349) [CraftServer.class:1.7.10-1614.176]
        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.jav
a:511) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.jav
a:485) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.jav
a:445) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(Dedicated
Server.java:336) [lt.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [M
inecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_71]

**Comment by caoli5288** [comment]
Cauldron's issue. May not break function.
