### ISSUE TITLE
"Can't call commit when autocommit=true"

### ISSUE THREAD

**Issue by krillr** [caoli5288/PlayerSQL#3]
[07:06:45 INFO]: __kazu__[/67.189.110.61:59620] logged in with entity id 302 at ([spawn]1042.5, 70.0, 689.5)
[07:06:45 WARN]: java.sql.SQLException: Can't call commit when autocommit=true
[07:06:45 WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
[07:06:45 WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
[07:06:45 WARN]: 	at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1655)
[07:06:45 WARN]: 	at com.mengcraft.playersql.task.LoadPlayerTask.run(LoadPlayerTask.java:42)
[07:06:45 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[07:06:45 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[07:06:45 WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by Cnly** [comment]
What version are you on?

**Comment by caoli5288** [comment]
thx
