### ISSUE TITLE
2.9版本的一个报错 

### ISSUE THREAD

**Issue by sumdream** [caoli5288/PlayerSQL#47]
`[20:49:13 WARN]: [PlayerSQL] Plugin PlayerSQL v2.9-SNAPSHOT generated an exception whilst handling plugin message
java.io.UTFDataFormatException: encoded string too long: 70892 bytes
        at java.io.DataOutputStream.writeUTF(Unknown Source) ~[?:1.8.0_152]
        at java.io.DataOutputStream.writeUTF(Unknown Source) ~[?:1.8.0_152]
        at com.mengcraft.playersql.PlayerDataHelper.write(PlayerDataHelper.java:57) ~[playersql-2.9-SNAPSHOT.jar:?]
        at com.mengcraft.playersql.PlayerDataHelper.encode(PlayerDataHelper.java:24) ~[playersql-2.9-SNAPSHOT.jar:?]
        at com.mengcraft.playersql.EventExecutor.lambda$new$1(EventExecutor.java:63) ~[playersql-2.9-SNAPSHOT.jar:?]
        at com.mengcraft.playersql.BiRegistry.handle(BiRegistry.java:26) ~[playersql-2.9-SNAPSHOT.jar:?]
        at com.mengcraft.playersql.EventExecutor.onPluginMessageReceived(EventExecutor.java:143) ~[playersql-2.9-SNAPSHOT.jar:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:426) [spigot-1.12.2-R0.1-SNAPS
HOT.jar:git-Spigot-eadd615-bea5a84]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2576) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-ea
dd615-bea5a84]
        at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:58) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-eadd61
5-bea5a84]
        at net.minecraft.server.v1_12_R1.PacketPlayInCustomPayload.a(SourceFile:8) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-eadd615
-bea5a84]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-eadd61
5-bea5a84]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_152]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_152]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-eadd615-bea5a84]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-eadd6
15-bea5a84]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-eadd6
15-bea5a84]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-eadd6
15-bea5a84]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2-R0.1-SNAPSHOT.jar:git-Spigot-ead
d615-bea5a84]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]`

**Comment by caoli5288** [comment]
收到

**Comment by DrPanic** [comment]
Same here. It was caused by many written books.

**Comment by caoli5288** [comment]
@DrPanic It's because of pluginmessage allow only 64k data per packet. 
I'll try compress data next version.

**Comment by Erumeldor** [comment]
#50

**Comment by Erumeldor** [comment]
Why do you close the issue, when there haven't been any changes that could fix it?

**Comment by caoli5288** [comment]
@Erumeldor I'll review it.
