### ISSUE TITLE
1.13 builds.

### ISSUE THREAD

**Issue by Marfjeh** [caoli5288/PlayerSQL#48]
Hey, i know that the plugin wont work on 1.13 but md_5 has released builds for the new api and on 1.13. recently i tried to load up the plugin on it and see whats going to happen and it throws this in the console:

```
[22:32:39 INFO]: [PlayerSQL] Enabling PlayerSQL v2.8-SNAPSHOT
[22:32:40 WARN]: [PlayerSQL] java.lang.IllegalAccessException: Class com.mengcraft.playersql.lib.ItemUtil$NMS can not access a member of class net.minecraft.server.v1_13_R1.ItemStack with modifiers "private"
[22:32:42 ERROR]: Error occurred while enabling PlayerSQL v2.8-SNAPSHOT (Is it up to date?)
java.lang.IllegalStateException: Hasn't compatible util! Update PlayerSQL or ProtocolLib
        at com.mengcraft.playersql.PluginMain.thr(PluginMain.java:148) ~[?:?]
        at com.mengcraft.playersql.lib.ItemUtilHandler.handle(ItemUtilHandler.java:38) ~[?:?]
        at com.mengcraft.playersql.PluginMain.onEnable(PluginMain.java:48) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13-pre7.jar:git-Spigot-6505f06-b8ea9ec]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13-pre7.jar:git-Spigot-6505f06-b8ea9ec]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13-pre7.jar:git-Spigot-6505f06-b8ea9ec]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:420) [spigot-1.13-pre7.jar:git-Spigot-6505f06-b8ea9ec]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:334) [spigot-1.13-pre7.jar:git-Spigot-6505f06-b8ea9ec]
        at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:523) [spigot-1.13-pre7.jar:git-Spigot-6505f06-b8ea9ec]
        at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:485) [spigot-1.13-pre7.jar:git-Spigot-6505f06-b8ea9ec]
        at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:384) [spigot-1.13-pre7.jar:git-Spigot-6505f06-b8ea9ec]
        at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288) [spigot-1.13-pre7.jar:git-Spigot-6505f06-b8ea9ec]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:647) [spigot-1.13-pre7.jar:git-Spigot-6505f06-b8ea9ec]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
```

I'm making this issue to make you aware of this issue :)

**Comment by caoli5288** [comment]
Will update after 1.13 release
