### ISSUE TITLE
Ebean-Error after installing VoxelSniper

### ISSUE THREAD

**Issue by DrPanic** [caoli5288/PlayerSQL#49]
Hey,

i have a problem after Installing Voxelsniper on our Server:

```
[22:46:46] [Server thread/INFO]: [PlayerSQL] Enabling PlayerSQL v2.8-SNAPSHOT
[22:46:47] [Server thread/INFO]: [PlayerSQL] Bukkit v1_12_R1
[22:46:47] [Server thread/INFO]: [PlayerSQL] Item util build-in
[22:46:47] [Server thread/INFO]: [PlayerSQL] ORM lib load okay!
[22:46:47] [Server thread/ERROR]: Error occurred while enabling PlayerSQL v2.8-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: com/avaje/ebean/config/dbplatform/SQLitePlatform
	at com.mengcraft.playersql.lib.simpleorm.EbeanManager.build(EbeanManager.java:39) ~[?:?]
	at com.mengcraft.playersql.lib.simpleorm.EbeanManager.getHandler(EbeanManager.java:25) ~[?:?]
	at com.mengcraft.playersql.PluginMain.onEnable(PluginMain.java:42) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1384]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1384]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1384]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) [patched_1.12.2.jar:git-Paper-1384]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1384]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1384]
	at java.lang.Thread.run(Thread.java:844) [?:?]
Caused by: java.lang.ClassNotFoundException: com.avaje.ebean.config.dbplatform.SQLitePlatform
	at java.net.URLClassLoader.findClass(URLClassLoader.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[patched_1.12.2.jar:git-Paper-1384]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1384]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:563) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[?:?]
	... 14 more
[22:46:47] [Server thread/INFO]: [PlayerSQL] Disabling PlayerSQL v2.8-SNAPSHOT
```

What can i do here? I mean, this has worked before some time.
Thanks

**Comment by YTiceice** [comment]
https://github.com/caoli5288/SimpleORM
