### ISSUE TITLE
java.lang.NoSuchMethodException: java.lang.Object.addURL(java.net.URL)

### ISSUE THREAD

**Issue by baba43** [caoli5288/PlayerSQL#53]
Hello,

thank you very much for the effort you put into this plugin.

We'd love to use PlayerSQL in the future, but we can't get it to work on our 1.13 server with Java 11. I'm not sure, what this error is related too, but with the latest build from Spigot I get this exception:

> [15:32:05] [Server thread/INFO]: [PlayerSQL] Enabling PlayerSQL v2.8-SNAPSHOT*
> [15:32:05] [Server thread/WARN]: [PlayerSQL] java.lang.IllegalAccessException: class com.mengcraft.playersql.lib.ItemUtil$NMS cannot access a member of class net.minecraft.server.v1_13_R2.ItemStack with modifiers "private"
> [15:32:05] [Server thread/INFO]: [PlayerSQL] Bukkit v1_13_R2
> [15:32:05] [Server thread/INFO]: [PlayerSQL] Item util protocollib
> [15:32:05] [Server thread/ERROR]: Error occurred while enabling PlayerSQL v2.8-SNAPSHOT (Is it up to date?)
> java.lang.NoSuchMethodException: java.lang.Object.addURL(java.net.URL)
> 	at java.lang.Class.getDeclaredMethod(Class.java:2476) ~[?:?]
> 	at com.mengcraft.playersql.lib.simpleorm.lib.RefHelper.getRef(RefHelper.java:41) ~[?:?]
> 	at com.mengcraft.playersql.lib.simpleorm.lib.RefHelper.lambda$getMethodRef$3(RefHelper.java:61) ~[?:?]
> 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[?:?]
> 	at com.mengcraft.playersql.lib.simpleorm.lib.RefHelper.getMethodRef(RefHelper.java:61) ~[?:?]
> 	at com.mengcraft.playersql.lib.simpleorm.lib.RefHelper.getRef(RefHelper.java:46) ~[?:?]
> 	at com.mengcraft.playersql.lib.simpleorm.lib.RefHelper.lambda$getMethodRef$3(RefHelper.java:61) ~[?:?]
> 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[?:?]
> 	at com.mengcraft.playersql.lib.simpleorm.lib.RefHelper.getMethodRef(RefHelper.java:61) ~[?:?]
> 	at com.mengcraft.playersql.lib.simpleorm.lib.RefHelper.getRef(RefHelper.java:46) ~[?:?]
> 	at com.mengcraft.playersql.lib.simpleorm.lib.RefHelper.lambda$getMethodRef$3(RefHelper.java:61) ~[?:?]
> 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[?:?]
> 	at com.mengcraft.playersql.lib.simpleorm.lib.RefHelper.getMethodRef(RefHelper.java:61) ~[?:?]
> 	at com.mengcraft.playersql.lib.simpleorm.lib.RefHelper.getRef(RefHelper.java:46) ~[?:?]
> 	at com.mengcraft.playersql.lib.simpleorm.lib.RefHelper.lambda$getMethodRef$3(RefHelper.java:61) ~[?:?]
> 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[?:?]
> 	at com.mengcraft.playersql.lib.simpleorm.lib.RefHelper.getMethodRef(RefHelper.java:61) ~[?:?]
> 	at com.mengcraft.playersql.lib.simpleorm.lib.RefHelper.getRef(RefHelper.java:46) ~[?:?]
> 	at com.mengcraft.playersql.lib.simpleorm.lib.RefHelper.lambda$getMethodRef$3(RefHelper.java:61) ~[?:?]
> 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[?:?]
> 	at com.mengcraft.playersql.lib.simpleorm.lib.RefHelper.getMethodRef(RefHelper.java:61) ~[?:?]
> 	at com.mengcraft.playersql.lib.simpleorm.lib.RefHelper.invoke(RefHelper.java:74) ~[?:?]
> 	at com.mengcraft.playersql.lib.simpleorm.lib.LibraryLoader.load(LibraryLoader.java:35) ~[?:?]
> 	at com.mengcraft.playersql.lib.simpleorm.lib.LibraryLoader.load(LibraryLoader.java:31) ~[?:?]
> 	at com.mengcraft.playersql.lib.simpleorm.ORM.loadExtLibrary(ORM.java:48) ~[?:?]
> 	at com.mengcraft.playersql.lib.simpleorm.ORM.loadLibrary(ORM.java:42) ~[?:?]
> 	at com.mengcraft.playersql.PluginMain.onEnable(PluginMain.java:51) ~[?:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[patched_1.13.2.jar:git-Paper-523]
> 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326) ~[patched_1.13.2.jar:git-Paper-523]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.2.jar:git-Paper-523]
> 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-523]
> 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-523]
> 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-523]
> 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-523]
> 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-523]
> 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-523]
> 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-523]
> 	at java.lang.Thread.run(Thread.java:834) [?:?]
> [15:32:05] [Server thread/INFO]: [PlayerSQL] Disabling PlayerSQL v2.8-SNAPSHOT

**Comment by caoli5288** [comment]
I'll review it tomorrow

**Comment by caoli5288** [comment]
Hi. It seems that you are not using the latest version.
Try https://github.com/caoli5288/PlayerSQL/releases/tag/2.10 and feedback plz.:-)

**Comment by baba43** [comment]
Hey, thanks for your fast reply. With that version, I get this error:

> [08:48:55] [Server thread/ERROR]: Could not load 'plugins/playersql-2.10-SNAPSHOT-all.jar' in folder 'plugins'
> org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/mengcraft/simpleorm/lib/Library
> 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.13.2.jar:git-Paper-523]
> 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.13.2.jar:git-Paper-523]
> 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) ~[patched_1.13.2.jar:git-Paper-523]
> 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331) ~[patched_1.13.2.jar:git-Paper-523]
> 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-523]
> 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-523]
> 	at java.lang.Thread.run(Thread.java:834) [?:?]
> Caused by: java.lang.NoClassDefFoundError: com/mengcraft/simpleorm/lib/Library
> 	at java.lang.Class.forName0(Native Method) ~[?:?]
> 	at java.lang.Class.forName(Class.java:398) ~[?:?]
> 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:62) ~[patched_1.13.2.jar:git-Paper-523]
> 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130) ~[patched_1.13.2.jar:git-Paper-523]
> 	... 6 more
> Caused by: java.lang.ClassNotFoundException: com.mengcraft.simpleorm.lib.Library
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
> 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:138) ~[patched_1.13.2.jar:git-Paper-523]
> 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84) ~[patched_1.13.2.jar:git-Paper-523]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
> 	at java.lang.Class.forName0(Native Method) ~[?:?]
> 	at java.lang.Class.forName(Class.java:398) ~[?:?]
> 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:62) ~[patched_1.13.2.jar:git-Paper-523]
> 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130) ~[patched_1.13.2.jar:git-Paper-523]
> 	... 6 more

**Comment by caoli5288** [comment]
Seems any blocked playersql download dependency? :-/
We use simpleorm as dependency now.
Install it manually may help.  https://github.com/caoli5288/SimpleORM/releases/tag/1.2.3

**Comment by baba43** [comment]
If I install that jar, I get the error from above:

> [09:03:39] [Server thread/INFO]: [PlayerSQL] Loading PlayerSQL v2.10-dev
> [09:03:39] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_13_R2.CraftServer] java.lang.Object.addURL(java.net.URL) initializing PlayerSQL v2.10-dev (Is it up to date?)
> java.lang.NoSuchMethodException: java.lang.Object.addURL(java.net.URL)
> 	at java.lang.Class.getDeclaredMethod(Class.java:2476) ~[?:?]
> 	at com.mengcraft.simpleorm.lib.Reflector.getRef(Reflector.java:44) ~[?:?]
> 	at com.mengcraft.simpleorm.lib.Reflector.lambda$getMethodRef$3(Reflector.java:64) ~[?:?]
> 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[?:?]
> 	at com.mengcraft.simpleorm.lib.Reflector.getMethodRef(Reflector.java:64) ~[?:?]
> 	at com.mengcraft.simpleorm.lib.Reflector.getRef(Reflector.java:49) ~[?:?]
> 	at com.mengcraft.simpleorm.lib.Reflector.lambda$getMethodRef$3(Reflector.java:64) ~[?:?]
> 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[?:?]
> 	at com.mengcraft.simpleorm.lib.Reflector.getMethodRef(Reflector.java:64) ~[?:?]
> 	at com.mengcraft.simpleorm.lib.Reflector.getRef(Reflector.java:49) ~[?:?]
> 	at com.mengcraft.simpleorm.lib.Reflector.lambda$getMethodRef$3(Reflector.java:64) ~[?:?]
> 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[?:?]
> 	at com.mengcraft.simpleorm.lib.Reflector.getMethodRef(Reflector.java:64) ~[?:?]
> 	at com.mengcraft.simpleorm.lib.Reflector.getRef(Reflector.java:49) ~[?:?]
> 	at com.mengcraft.simpleorm.lib.Reflector.lambda$getMethodRef$3(Reflector.java:64) ~[?:?]
> 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[?:?]
> 	at com.mengcraft.simpleorm.lib.Reflector.getMethodRef(Reflector.java:64) ~[?:?]
> 	at com.mengcraft.simpleorm.lib.Reflector.getRef(Reflector.java:49) ~[?:?]
> 	at com.mengcraft.simpleorm.lib.Reflector.lambda$getMethodRef$3(Reflector.java:64) ~[?:?]
> 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[?:?]
> 	at com.mengcraft.simpleorm.lib.Reflector.getMethodRef(Reflector.java:64) ~[?:?]
> 	at com.mengcraft.simpleorm.lib.Reflector.invoke(Reflector.java:83) ~[?:?]
> 	at com.mengcraft.simpleorm.lib.LibraryLoader.load(LibraryLoader.java:35) ~[?:?]
> 	at com.mengcraft.playersql.PluginMain.onLoad(PluginMain.java:49) ~[?:?]
> 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:336) ~[patched_1.13.2.jar:git-Paper-523]
> 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-523]
> 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-523]
> 	at java.lang.Thread.run(Thread.java:834) [?:?]

with

> [09:03:39] [Server thread/INFO]: [SimpleORM] Loading SimpleORM v1.2.3
> [09:03:39] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_13_R2.CraftServer] java.lang.Object.addURL(java.net.URL) initializing SimpleORM v1.2.3 (Is it up to date?)
> java.lang.NoSuchMethodException: java.lang.Object.addURL(java.net.URL)

**Comment by caoli5288** [comment]
Seems jdk11 compatible issues. I'll check it later.

**Comment by baba43** [comment]
Hey, thank you very much for your efforts.

Do you think that you might check this issue in the near future?

**Comment by caoli5288** [comment]
Within this week

**Comment by caoli5288** [comment]
Try http://ci.mengcraft.com:8081/job/SimpleORM/lastSuccessfulBuild/artifact/target/simpleorm-1.2-SNAPSHOT.jar

**Comment by baba43** [comment]
> [10:06:34] [Server thread/INFO]: [PlayerSQL] Loading PlayerSQL v2.10-dev
[10:06:34] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_13_R2.CraftServer] com.mengcraft.simpleorm.lib.LibraryLoader.load(Lorg/bukkit/plugin/java/JavaPlugin;Lcom/mengcraft/simpleorm/lib/Library;Z)V initializing PlayerSQL v2.10-dev (Is it up to date?)
java.lang.NoSuchMethodError: com.mengcraft.simpleorm.lib.LibraryLoader.load(Lorg/bukkit/plugin/java/JavaPlugin;Lcom/mengcraft/simpleorm/lib/Library;Z)V
	at com.mengcraft.playersql.PluginMain.onLoad(PluginMain.java:49) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:336) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-540]
	at java.lang.Thread.run(Thread.java:834) [?:?]

Then, a join failes due do this error:

> [10:11:46] [Server thread/INFO]: baba43[/37.201.192.94:49867] logged in with entity id 982 at ([lobby]-121.34310355775722, 102.0, 201.42259244341713)
[10:11:46] [Server thread/INFO]: baba43 lost connection: Your game data loading error, please contact the operator
[10:11:46] [Server thread/INFO]: [PlayerSQL] io.netty.handler.codec.EncoderException: java.io.EOFException

**Comment by caoli5288** [comment]
My mistake. http://ci.mengcraft.com:8081/job/SimpleORM/84/artifact/target/simpleorm-1.2-SNAPSHOT.jar

**Comment by baba43** [comment]
Fine. The first exception is gone and the plugin seems to load correctly.

However, I still can't connect to the server if PlayerSQL is activated. The log only shows this:

> [12:20:08] [Server thread/INFO]: baba43[/37.201.192.94:55063] logged in with entity id 898 at ([lobby]-121.37479915672478, 102.0, 197.69561495166292)
[12:20:08] [Server thread/INFO]: baba43 lost connection: Your game data loading error, please contact the operator
[12:20:08] [Server thread/INFO]: [PlayerSQL] io.netty.handler.codec.EncoderException: java.io.EOFException
[12:20:08] [Server thread/WARN]: handleDisconnection() called twice

**Comment by caoli5288** [comment]
You upgrade spigot from lower version?

**Comment by baba43** [comment]
@caoli5288 yes. I've tested it out. After deleting my database entry, it works. However, when trying to upgrade from our current version (2.8) to your latest snapshot (2.10), players can't join due to this exception:

> [09:54:05] [Server thread/INFO]: [PlayerSQL] ### recv peer_ready
[09:54:05] [Craft Scheduler Thread - 78/INFO]: [PlayerSQL] Load user baba43 done.
[09:54:05] [Craft Scheduler Thread - 78/INFO]: [PlayerSQL] Update aa201d00-2389-4ef6-ab0e-e8443e473d5d lock to true okay
[09:54:05] [Server thread/INFO]: baba43 lost connection: Your game data loading error, please contact the operator
[09:54:05] [ForkJoinPool.commonPool-worker-31/INFO]: [PlayerSQL] Update aa201d00-2389-4ef6-ab0e-e8443e473d5d lock to false okay
[09:54:05] [Server thread/ERROR]: [PlayerSQL] io.netty.handler.codec.EncoderException: java.io.EOFException
io.netty.handler.codec.EncoderException: java.io.EOFException
	at net.minecraft.server.v1_13_R2.PacketDataSerializer.j(PacketDataSerializer.java:236) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.PacketDataSerializer.k(PacketDataSerializer.java:283) ~[patched_1.13.2.jar:git-Paper-540]
	at com.mengcraft.playersql.internal.v1_13_2.PacketDataSerializer.readItemStack(PacketDataSerializer.java:43) ~[?:?]
	at com.mengcraft.playersql.DataSerializer.deserialize(DataSerializer.java:54) ~[?:?]
	at com.mengcraft.playersql.UserManager.toStack(UserManager.java:257) ~[?:?]
	at com.mengcraft.playersql.UserManager.pend(UserManager.java:186) ~[?:?]
	at com.mengcraft.playersql.UserManager.pend(UserManager.java:169) ~[?:?]
	at com.mengcraft.playersql.UserManager.lambda$addFetched$0(UserManager.java:39) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-540]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-540]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:202) ~[?:?]
	at java.io.DataInputStream.readUTF(DataInputStream.java:614) ~[?:?]
	at java.io.DataInputStream.readUTF(DataInputStream.java:569) ~[?:?]
	at net.minecraft.server.v1_13_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:82) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:54) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.PacketDataSerializer.j(PacketDataSerializer.java:234) ~[patched_1.13.2.jar:git-Paper-540]
	... 14 more

**Comment by caoli5288** [comment]
Because 2.8.x use protocollib encode itemstack. This may fix. https://github.com/caoli5288/PlayerSQL/releases/tag/jenkins-PlayerSQLGradle-39

**Comment by JOO200** [comment]
Using the linked jar-version, with and without ProtocolLib:
```[21:23:56] [User Authenticator #1/INFO]: UUID of player Joo200 is 254c41f4-f1b4-4ae8-ae76-ba92a4983fbc
[21:23:57] [Server thread/INFO]: [PlayerSQL] Lock user 254c41f4-f1b4-4ae8-ae76-ba92a4983fbc done!
[21:23:57] [Server thread/INFO]: Joo200[/178.4.96.55:59729] logged in with entity id 874 at ([lobby]-128.08817844958696, 125.49168873954233, 170.87296856446204)
[21:23:57] [Craft Scheduler Thread - 1/INFO]: [PlayerSQL] Load user Joo200 done.
[21:23:57] [Server thread/INFO]: Joo200 lost connection: Your game data loading error, please contact the operator
[21:23:57] [Craft Scheduler Thread - 1/INFO]: [PlayerSQL] Update 254c41f4-f1b4-4ae8-ae76-ba92a4983fbc lock to true okay
[21:23:57] [ForkJoinPool.commonPool-worker-5/INFO]: [PlayerSQL] Update 254c41f4-f1b4-4ae8-ae76-ba92a4983fbc lock to false okay
[21:23:57] [Server thread/ERROR]: [PlayerSQL] java.lang.RuntimeException: An internal error occured.
java.lang.RuntimeException: An internal error occured.
	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20) ~[?:?]
	at com.comphenix.protocol.utility.StreamSerializer.deserializeItemStack(StreamSerializer.java:348) ~[?:?]
	at com.mengcraft.playersql.DataSerializer.deserialize(DataSerializer.java:58) ~[?:?]
	at com.mengcraft.playersql.UserManager.toStack(UserManager.java:257) ~[?:?]
	at com.mengcraft.playersql.UserManager.pend(UserManager.java:186) ~[?:?]
	at com.mengcraft.playersql.UserManager.pend(UserManager.java:169) ~[?:?]
	at com.mengcraft.playersql.UserManager.lambda$addFetched$0(UserManager.java:39) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-540]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-540]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: io.netty.handler.codec.EncoderException: java.io.EOFException
	at net.minecraft.server.v1_13_R2.PacketDataSerializer.j(PacketDataSerializer.java:236) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.PacketDataSerializer.k(PacketDataSerializer.java:283) ~[patched_1.13.2.jar:git-Paper-540]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16) ~[?:?]
	... 13 more
Caused by: java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:202) ~[?:?]
	at java.io.DataInputStream.readUTF(DataInputStream.java:614) ~[?:?]
	at java.io.DataInputStream.readUTF(DataInputStream.java:569) ~[?:?]
	at net.minecraft.server.v1_13_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:82) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:54) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.PacketDataSerializer.j(PacketDataSerializer.java:234) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.PacketDataSerializer.k(PacketDataSerializer.java:283) ~[patched_1.13.2.jar:git-Paper-540]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16) ~[?:?]
	... 13 more
[21:23:57] [Server thread/WARN]: handleDisconnection() called twice
[21:23:57] [Server thread/INFO]: Stats für Joo200 gespeichert!```

**Comment by caoli5288** [comment]
@JOO200 I'm not very sure how to reprodce that :-(.
I tried to upgrade from 2.8 to 2.10, and everything worked well.

**Comment by baba43** [comment]
@caoli5288 maybe you can give it a try with my sample. If I put a simple dirt block into my inventory and into my enderchest, our current version (2.8) my data looks like this:
https://nopaste.xyz/?2aa9ced4257a47b0#SJxT0C3ROz6X7VNy+hQG0bbXNGNrpzXw2CmX86ntSRE=

If I copy that data to our testserver (with 2.10) it fails:

```
[11:55:06] [Craft Scheduler Thread - 21/INFO]: [PlayerSQL] Load user baba43 fail 1.
[11:55:07] [Craft Scheduler Thread - 23/INFO]: [PlayerSQL] Load user baba43 fail 2.
[11:55:07] [Craft Scheduler Thread - 22/INFO]: [PlayerSQL] Load user baba43 fail 3.
[11:55:08] [Craft Scheduler Thread - 23/INFO]: [PlayerSQL] Load user baba43 fail 4.
[11:55:08] [Craft Scheduler Thread - 23/INFO]: [PlayerSQL] Load user baba43 fail 5.
[11:55:09] [Craft Scheduler Thread - 23/INFO]: [PlayerSQL] Load user baba43 fail 6.
[11:55:09] [Craft Scheduler Thread - 23/INFO]: [PlayerSQL] Load user baba43 fail 7.
[11:55:10] [Craft Scheduler Thread - 23/INFO]: [PlayerSQL] Load user baba43 fail 8.
[11:55:10] [Craft Scheduler Thread - 23/INFO]: [PlayerSQL] Load user baba43 done.
[11:55:10] [Craft Scheduler Thread - 23/INFO]: [PlayerSQL] Update aa201d00-2389-4ef6-ab0e-e8443e473d5d lock to true okay
[11:55:10] [Server thread/INFO]: baba43 lost connection: Your game data loading error, please contact the operator
[11:55:10] [ForkJoinPool.commonPool-worker-5/INFO]: [PlayerSQL] Update aa201d00-2389-4ef6-ab0e-e8443e473d5d lock to false okay
[11:55:10] [Server thread/ERROR]: [PlayerSQL] io.netty.handler.codec.EncoderException: java.io.EOFException
io.netty.handler.codec.EncoderException: java.io.EOFException
	at net.minecraft.server.v1_13_R2.PacketDataSerializer.j(PacketDataSerializer.java:236) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.PacketDataSerializer.k(PacketDataSerializer.java:283) ~[patched_1.13.2.jar:git-Paper-540]
	at com.mengcraft.playersql.internal.v1_13_2.PacketDataSerializer.readItemStack(PacketDataSerializer.java:43) ~[?:?]
	at com.mengcraft.playersql.DataSerializer.deserialize(DataSerializer.java:54) ~[?:?]
	at com.mengcraft.playersql.UserManager.toStack(UserManager.java:257) ~[?:?]
	at com.mengcraft.playersql.UserManager.pend(UserManager.java:186) ~[?:?]
	at com.mengcraft.playersql.UserManager.pend(UserManager.java:169) ~[?:?]
	at com.mengcraft.playersql.UserManager.lambda$addFetched$0(UserManager.java:39) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-540]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-540]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:202) ~[?:?]
	at java.io.DataInputStream.readUTF(DataInputStream.java:614) ~[?:?]
	at java.io.DataInputStream.readUTF(DataInputStream.java:569) ~[?:?]
	at net.minecraft.server.v1_13_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:82) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:54) ~[patched_1.13.2.jar:git-Paper-540]
	at net.minecraft.server.v1_13_R2.PacketDataSerializer.j(PacketDataSerializer.java:234) ~[patched_1.13.2.jar:git-Paper-540]
	... 14 more

```

**Comment by baba43** [comment]
What ProtocolLib are you testing with? 
May this be the source of problem? 

We use 4.4.0.

**Comment by baba43** [comment]
I think the problem is that you always try to deserialize inventories by using the current internal serializer (so does ProtocolLib). So when running PlayerSQL / ProtocolLib with 1.13, none of these plugins try to deserialize inventories using the 1.12 deserializer. 

So in my opinion, the solution could be to include the 1.12 packages in ONE major PlayerSQL version that is capable of converting old database entries to new ones. That version must contain 1.12 and 1.13 serializers at the same time, obviously. 

Do you think that is possible?

**Comment by caoli5288** [comment]
> none of these plugins try to deserialize inventories using the 1.12 deserializer.

No. Both 1.12.x and 1.13.x's internal serializer are supported. We try internel lib only version matched so 1.13 will always try 1.13's.
1.13's internel serializer can read 1.12's data(not sure inversed). It's mojang's codes.

**Comment by caoli5288** [comment]
closed
