### ISSUE TITLE
更新到最新版本出现错误

### ISSUE THREAD

**Issue by Xuwznln** [caoli5288/PlayerSQL#54]
问题一：升级新版本时出错
旧版本成功：
[12:24:22] [User Authenticator #1/INFO]: UUID of player Xu_wznln_2017 is 2a3b9874-d6b2-3a83-94e7-0db6a5b3e66e
[12:24:22] [Server thread/INFO]: [PlayerSQL] Lock user 2a3b9874-d6b2-3a83-94e7-0db6a5b3e66e done!
[12:24:22] [Server thread/INFO]: Xu_wznln_2017[/112.96.248.14:52631] logged in with entity id 311 at ([world]22497.74618032058, 60.0, -7735.293136029611)
[12:24:22] [Craft Scheduler Thread - 2/INFO]: [PlayerSQL] Load user Xu_wznln_2017 done.
[12:24:22] [Craft Scheduler Thread - 2/INFO]: [PlayerSQL] Update 2a3b9874-d6b2-3a83-94e7-0db6a5b3e66e lock to true okay
[12:24:22] [Server thread/INFO]: [PlayerSQL] Scheduling daily save task for user 2a3b9874-d6b2-3a83-94e7-0db6a5b3e66e.
新版本报错
[12:21:21] [User Authenticator #1/INFO]: UUID of player Xu_wznln_2017 is 2a3b9874-d6b2-3a83-94e7-0db6a5b3e66e
[12:21:22] [Server thread/INFO]: [PlayerSQL] Lock user 2a3b9874-d6b2-3a83-94e7-0db6a5b3e66e done!
[12:21:22] [Server thread/INFO]: Xu_wznln_2017[/112.96.248.14:65364] logged in with entity id 311 at ([world]22497.74618032058, 60.0, -7735.293136029611)
[12:21:22] [Craft Scheduler Thread - 0/INFO]: [PlayerSQL] Load user Xu_wznln_2017 done.
[12:21:22] [Craft Scheduler Thread - 0/INFO]: [PlayerSQL] Update 2a3b9874-d6b2-3a83-94e7-0db6a5b3e66e lock to true okay
[12:21:22] [Server thread/INFO]: Xu_wznln_2017 lost connection: Your game data loading error, please contact the operator
[12:21:22] [ForkJoinPool.commonPool-worker-25/INFO]: [PlayerSQL] Update 2a3b9874-d6b2-3a83-94e7-0db6a5b3e66e lock to false okay
[12:21:22] [Server thread/INFO]: Xu_wznln_2017 left the game
[12:21:22] [Server thread/ERROR]: [PlayerSQL] java.lang.IllegalArgumentException: Illegal base64 character d
java.lang.IllegalArgumentException: Illegal base64 character d
	at java.util.Base64$Decoder.decode0(Base64.java:714) ~[?:1.8.0_201]
	at java.util.Base64$Decoder.decode(Base64.java:526) ~[?:1.8.0_201]
	at java.util.Base64$Decoder.decode(Base64.java:549) ~[?:1.8.0_201]
	at com.mengcraft.playersql.DataSerializer.deserialize(DataSerializer.java:54) ~[?:?]
	at com.mengcraft.playersql.UserManager.toStack(UserManager.java:259) ~[?:?]
	at com.mengcraft.playersql.UserManager.pend(UserManager.java:188) ~[?:?]
	at com.mengcraft.playersql.UserManager.pend(UserManager.java:171) ~[?:?]
	at com.mengcraft.playersql.UserManager.lambda$addFetched$0(UserManager.java:40) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[Survival-1paper1.13.jar:git-Paper-625]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[Survival-1paper1.13.jar:git-Paper-625]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[Survival-1paper1.13.jar:git-Paper-625]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[Survival-1paper1.13.jar:git-Paper-625]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[Survival-1paper1.13.jar:git-Paper-625]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[Survival-1paper1.13.jar:git-Paper-625]
	at java.lang.Thread.run(Thread.java:748) 

问题2： 不管是用哪个版本，同样的数据，1.13和1.14玩家实际物品并不一致

**Comment by caoli5288** [comment]
先回答问题2吧。是这样的，playersql一直不确保大版本之间能完全兼容，因为是直接调用的spigot本身的序列化接口，如果版本改了物品序列化接口就直接gg了。

**Comment by caoli5288** [comment]
你是不是从2.10升上来的？

**Comment by Xuwznln** [comment]
是

**Comment by caoli5288** [comment]
之前版本默认使用protocollib进行序列化的，我加个选项调整默认使用protocollib吧

**Comment by Xuwznln** [comment]
ok,多谢，那么上面说的升级版本的方式是不是可行呢？

**Comment by caoli5288** [comment]
https://github.com/caoli5288/PlayerSQL/releases/tag/b41

加了个选项，`plugin.use-protocollib-default`

> ok,多谢，那么上面说的升级版本的方式是不是可行呢？

不是太可行，除非你服务器是原地上下线的

**Comment by Xuwznln** [comment]
我现在测试一下

**Comment by Xuwznln** [comment]
可以进了，但是好像物品不同步了

**Comment by Xuwznln** [comment]
[14:48:02] [Server thread/ERROR]: Error occurred while enabling PlayerSQL v2.10-dev (Is it up to date?)
java.lang.IllegalArgumentException: Illegal character in opaque part at index 19: jdbc:sqlite:plugins\PlayerSQL\local_transfer.sqlite
	at java.net.URI.create(URI.java:852) ~[?:1.8.0_201]
	at com.mengcraft.simpleorm.driver.IDatabaseDriver.validAndLoad(IDatabaseDriver.java:31) ~[?:?]
	at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:181) ~[?:?]
	at com.mengcraft.playersql.PluginMain.onEnable(PluginMain.java:99) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[Survival-1paper1.13.jar:git-Paper-625]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[Survival-1paper1.13.jar:git-Paper-625]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[Survival-1paper1.13.jar:git-Paper-625]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[Survival-1paper1.13.jar:git-Paper-625]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[Survival-1paper1.13.jar:git-Paper-625]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[Survival-1paper1.13.jar:git-Paper-625]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[Survival-1paper1.13.jar:git-Paper-625]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[Survival-1paper1.13.jar:git-Paper-625]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[Survival-1paper1.13.jar:git-Paper-625]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[Survival-1paper1.13.jar:git-Paper-625]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by caoli5288** [comment]
哦，，好像是windows系统路径问题，，

**Comment by Xuwznln** [comment]
删除就好了
这个更新版本无效可就了吗

**Comment by caoli5288** [comment]
版本更新看mojang心情了，我决定不了

**Comment by Xuwznln** [comment]
我们服务器是必须要求玩家先进一个服，才能进其他背包同步的服，这样子这个升级版本按照上面的理论就ok了吧

**Comment by caoli5288** [comment]
是ok的

**Comment by Xuwznln** [comment]
十分感谢
