### ISSUE TITLE
加载出错

### ISSUE THREAD

**Issue by 3269199948** [caoli5288/PlayerSQL#57]
Could not load 'plugins/[P][同步]Playersql.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/mengcraft/simpleorm/lib/Library
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[Spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[Spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [Spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [Spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [Spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [Spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.NoClassDefFoundError: com/mengcraft/simpleorm/lib/Library
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_232]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_232]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[Spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[Spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: com.mengcraft.simpleorm.lib.Library
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_232]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[Spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[Spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_232]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_232]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[Spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[Spigot-1.12.2.jar:git-Spigot-642f6d2-57ab4cf]
        ... 6 more

**Comment by caoli5288** [comment]
You may needs the `SimpleORM`. See https://github.com/caoli5288/SimpleORM/releases
