### ISSUE TITLE
PSQL v2.10加载时出现问题

### ISSUE THREAD

**Issue by Mr-Notch** [caoli5288/PlayerSQL#58]
[22:26:12 INFO]: [PlayerSQL] Load library lib\javax\persistence\persistence-api\persistence-api-1.0.jar done
[22:26:12 INFO]: [PlayerSQL] Load library lib\org\avaje\ebean\ebean-2.8.1.jar done
[22:26:12 INFO]: [PlayerSQL] ORM lib load okay!
[22:26:12 ERROR]: 启用 PlayerSQL v2.10-dev 时发生错误 (它是最新的吗？)
 java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at com.zaxxer.hikari.HikariConfig.<clinit>(HikariConfig.java:51) ~[HikariConfig.class:?]
        at com.mengcraft.simpleorm.EbeanHandler.createSource(EbeanHandler.java:164) ~[?:?]
        at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:201) ~[?:?]
        at com.mengcraft.playersql.PluginMain.onEnable(PluginMain.java:86) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) ~[JavaPlugin.class:7464a42]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [JavaPluginLoader.class:7464a42]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399) [SimplePluginManager.class:7464a42]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:466) [CraftServer.class:7464a42]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:407) [CraftServer.class:7464a42]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:393) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:321) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:599) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:110) ~[Mohist-7464a42-server.jar:7464a42]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
        ... 13 more

使用Mohist服务端核心（类CAT高版本PF服务端）：
[]https://ci.codemc.io/job/Mohist-Community/job/Mohist-1.12.2/

**Comment by caoli5288** [comment]
这个插件的libraries貌似没有包括slf4j，你可以下载一个对应的库，放进libraries目录。

不过就算能启动，原则上我的插件是只兼容spigot的，强行用在mod服可能会有位置问题。
