### ISSUE TITLE
lib无法获取

### ISSUE THREAD

**Issue by smyhw** [caoli5288/PlayerSQL#60]
老哥你ci好像被机房屏蔽了
playersql的lib都下载不下来
能不能直接把lib打个包放到其他地方下载.....
现在就是:
`Caused by: java.io.FileNotFoundException: http://ci.mengcraft.com:8080/plugin/repository/everything/org/avaje/ebean/2.8.1/ebean-2.8.1.jar
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_221]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_221]
        at java.net.URL.openStream(Unknown Source) ~[?:1.8.0_221]
        at com.mengcraft.playersql.lib.simpleorm.lib.MavenLibrary.loadFile(MavenLibrary.java:114) ~[?:?]`

浏览器访问上去就是机房的拦截页面

**Comment by caoli5288** [comment]
更新下版本
