### ISSUE TITLE
 ERROR

### ISSUE THREAD

**Issue by xXjojojXx** [caoli5288/PlayerSQL#63]
[12:44:20 INFO]: [PlayerSQL] ORM lib load okay!
[12:44:20 WARN]: [SimpleORM] Loaded class com.zaxxer.hikari.HikariDataSource from lightEconomy v2.8.4 which is not a depend, softdepend or loadbefore of this plugin.
[12:44:20 ERROR]: [com.avaje.ebean.config.PropertyMapLoader] ebean.properties not found
[12:44:20 INFO]: [com.zaxxer.hikari.HikariDataSource] PlayerSQL@13220db5-6a2a-45f9-b606-c7372673b56b - Starting...
[12:44:21 ERROR]: [com.zaxxer.hikari.pool.HikariPool] PlayerSQL@13220db5-6a2a-45f9-b606-c7372673b56b - Exception during pool initialization.
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[patched_1.16.4.jar:git-Paper-294]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933) ~[patched_1.16.4.jar:git-Paper-294]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869) ~[patched_1.16.4.jar:git-Paper-294]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:864) ~[patched_1.16.4.jar:git-Paper-294]
        at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1707) ~[patched_1.16.4.jar:git-Paper-294]
        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1217) ~[patched_1.16.4.jar:git-Paper-294]
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189) ~[patched_1.16.4.jar:git-Paper-294]
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220) ~[patched_1.16.4.jar:git-Paper-294]        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015) ~[patched_1.16.4.jar:git-Paper-294]
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768) ~[patched_1.16.4.jar:git-Paper-294]
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[patched_1.16.4.jar:git-Paper-294]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_261]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_261]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:403) ~[patched_1.16.4.jar:git-Paper-294]
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385) ~[patched_1.16.4.jar:git-Paper-294]
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323) ~[patched_1.16.4.jar:git-Paper-294]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[?:?]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358) ~[?:?]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[?:?]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[?:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.checkDataSource(DefaultServerFactory.java:472) ~[ebean-2.8.1.jar:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:170) ~[ebean-2.8.1.jar:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:63) ~[ebean-2.8.1.jar:?]
        at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) ~[ebean-2.8.1.jar:?]
        at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:272) ~[?:?]
        at com.mengcraft.playersql.PluginMain.onEnable(PluginMain.java:93) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-294]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-294]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-294]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-294]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940) ~[patched_1.16.4.jar:git-Paper-294]        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-294]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
[12:44:21 ERROR]: Error occurred while enabling PlayerSQL v2.10-dev (Is it up to date?)
com.mengcraft.simpleorm.DatabaseException: javax.persistence.PersistenceException: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
        at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:274) ~[?:?]
        at com.mengcraft.playersql.PluginMain.onEnable(PluginMain.java:93) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-294]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-294]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-294]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-294]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-294]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:940) ~[patched_1.16.4.jar:git-Paper-294]        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-294]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: javax.persistence.PersistenceException: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.checkDataSource(DefaultServerFactory.java:482) ~[ebean-2.8.1.jar:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:170) ~[ebean-2.8.1.jar:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:63) ~[ebean-2.8.1.jar:?]
        at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) ~[ebean-2.8.1.jar:?]
        at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:272) ~[?:?]
        ... 11 more
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[patched_1.16.4.jar:git-Paper-294]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933) ~[patched_1.16.4.jar:git-Paper-294]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869) ~[patched_1.16.4.jar:git-Paper-294]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:864) ~[patched_1.16.4.jar:git-Paper-294]
        at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1707) ~[patched_1.16.4.jar:git-Paper-294]
        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1217) ~[patched_1.16.4.jar:git-Paper-294]
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189) ~[patched_1.16.4.jar:git-Paper-294]
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220) ~[patched_1.16.4.jar:git-Paper-294]        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015) ~[patched_1.16.4.jar:git-Paper-294]
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768) ~[patched_1.16.4.jar:git-Paper-294]
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[patched_1.16.4.jar:git-Paper-294]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_261]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_261]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_261]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:403) ~[patched_1.16.4.jar:git-Paper-294]
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385) ~[patched_1.16.4.jar:git-Paper-294]
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323) ~[patched_1.16.4.jar:git-Paper-294]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[?:?]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358) ~[?:?]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[?:?]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[?:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.checkDataSource(DefaultServerFactory.java:472) ~[ebean-2.8.1.jar:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:170) ~[ebean-2.8.1.jar:?]
        at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:63) ~[ebean-2.8.1.jar:?]
        at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) ~[ebean-2.8.1.jar:?]
        at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:272) ~[?:?]
        ... 11 more

**Comment by caoli5288** [comment]
Check your config.yml's dataSource settings
