### ISSUE TITLE
加载出错

### ISSUE THREAD

**Issue by beamwu** [caoli5288/PlayerSQL#64]
[22:43:27] [Server thread/INFO]: [PlayerSQL] Enabling PlayerSQL v2.10-dev
[22:43:27] [Server thread/INFO]: PACKET_DATA_SERIALIZER_FACTORY = null
[22:43:27] [Server thread/INFO]: [PlayerSQL] Load library lib/javax/persistence/persistence-api/persistence-api-1.0.jar done
[22:43:27] [Server thread/INFO]: [PlayerSQL] Load library lib/org/avaje/ebean/ebean-2.8.1.jar done
[22:43:27] [Server thread/INFO]: [PlayerSQL] ORM lib load okay!
[22:43:27] [Server thread/ERROR]: ebean.properties not found
[22:43:27] [Server thread/ERROR]: Error occurred while enabling PlayerSQL v2.10-dev (Is it up to date?)
java.lang.NoClassDefFoundError: com/avaje/ebean/EbeanServer
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_251]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_251]
        at com.avaje.ebeaninternal.api.ClassLoadContext.forName(ClassLoadContext.java:68) ~[ClassLoadContext.class:?]
        at com.avaje.ebeaninternal.api.ClassUtil.forName(ClassUtil.java:53) ~[ClassUtil.class:?]
        at com.avaje.ebeaninternal.api.ClassUtil.newInstance(ClassUtil.java:103) ~[ClassUtil.class:?]
        at com.avaje.ebeaninternal.api.ClassUtil.newInstance(ClassUtil.java:94) ~[ClassUtil.class:?]
        at com.avaje.ebean.EbeanServerFactory.createServerFactory(EbeanServerFactory.java:112) ~[EbeanServerFactory.class:?]
        at com.avaje.ebean.EbeanServerFactory.<clinit>(EbeanServerFactory.java:57) ~[EbeanServerFactory.class:?]
        at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:242) ~[?:?]
        at com.mengcraft.playersql.PluginMain.onEnable(PluginMain.java:93) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-83d81a7]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-83d81a7]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-83d81a7]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:437) [CraftServer.class:git-CatServer-1.12.2-83d81a7]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:385) [CraftServer.class:git-CatServer-1.12.2-83d81a7]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:384) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:596) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: java.lang.ClassNotFoundException: com.avaje.ebean.EbeanServer
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_251]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_251]
        ... 19 more

**Comment by caoli5288** [comment]
从报错看你使用的版本有一段时间了，试试最新版？
https://github.com/caoli5288/PlayerSQL/releases/download/2.11-20201125.1/playersql-2.11-SNAPSHOT.jar

需要最新simpleorm，
https://github.com/caoli5288/SimpleORM/releases/download/b118/simpleorm-1.4-SNAPSHOT.jar

**Comment by beamwu** [comment]
用最新的也试过了才换旧版本的  报错是一样的

**Comment by caoli5288** [comment]
注意到你是mod服，因为mod服务端种类太多没办法测试到兼容性，抱歉
