### ISSUE TITLE
Error occurred while enabling PlayerSQL

### ISSUE THREAD

**Issue by Corneus123** [caoli5288/PlayerSQL#65]
I got an error when using the newest version one on the website, and it gives me this error
The one in [here](https://www.spigotmc.org/resources/playersql.552/)

> [09:41:03 ERROR]: Error occurred while enabling PlayerSQL v2.10-dev (Is it up to date?)
java.lang.IllegalAccessError: class com.avaje.ebean.EbeanServerFactory tried to access protected method 'void com.avaje.ebean.Ebean.register(com.avaje.ebean.EbeanServer, boolean)' (com.avaje.ebean.EbeanServerFactory is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @cefeac7; com.avaje.ebean.Ebean is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @45e2688a)
        at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:84) ~[?:?]
        at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:272) ~[?:?]
        at com.mengcraft.playersql.PluginMain.onEnable(PluginMain.java:93) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-463]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-463]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-463]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.5.jar:git-Paper-463]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.5.jar:git-Paper-463]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:465) ~[patched_1.16.5.jar:git-Paper-463]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.5.jar:git-Paper-463]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.5.jar:git-Paper-463]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-463]
        at java.lang.Thread.run(Thread.java:834) [?:?]
        
Is there's another newer version? the version that i download said V2.11 instead the one that installed is V2.10-dev
Thank you in advance

**Comment by caoli5288** [comment]
fixed
