### ISSUE TITLE
PlayerSQL 2.11.3 Error

### ISSUE THREAD

**Issue by xPoyraz** [caoli5288/PlayerSQL#67]
```
[15:14:35] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to PlayerSQL v2.11-SNAPSHOT
java.lang.ExceptionInInitializerError: null
	at com.mengcraft.playersql.EventExecutor.handle(EventExecutor.java:98) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor98.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-969]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-969]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-969]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-969]
	at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:273) ~[patched_1.16.5.jar:git-Purpur-969]
	at net.minecraft.server.v1_16_R3.PlayerList.lambda$a$1(PlayerList.java:220) ~[patched_1.16.5.jar:git-Purpur-969]
	at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:168) ~[patched_1.16.5.jar:git-Purpur-969]
	at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:540) ~[patched_1.16.5.jar:git-Purpur-969]
	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:150) ~[patched_1.16.5.jar:git-Purpur-969]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1461) ~[patched_1.16.5.jar:git-Purpur-969]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:387) ~[patched_1.16.5.jar:git-Purpur-969]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1284) ~[patched_1.16.5.jar:git-Purpur-969]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1010) ~[patched_1.16.5.jar:git-Purpur-969]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176) ~[patched_1.16.5.jar:git-Purpur-969]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
	at com.mengcraft.playersql.Utils.getInterface(Utils.java:27) ~[?:?]
	at com.mengcraft.playersql.Utils.<clinit>(Utils.java:17) ~[?:?]
	... 17 more
```

When I update to the latest version I get an error like this @caoli5288

**Comment by caoli5288** [comment]
What your java version?

**Comment by xPoyraz** [comment]
```
[19:14:19] [User Authenticator #2/INFO]: UUID of player mehmetx1 is 06402dcb-5167-3498-bbad-359eca293f11
[19:14:19] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to PlayerSQL v2.11.4
java.lang.NoClassDefFoundError: Could not initialize class com.mengcraft.playersql.Utils
	at com.mengcraft.playersql.EventExecutor.handle(EventExecutor.java:98) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor98.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-969]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-969]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-969]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-969]
	at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:273) ~[patched_1.16.5.jar:git-Purpur-969]
	at net.minecraft.server.v1_16_R3.PlayerList.lambda$a$1(PlayerList.java:220) ~[patched_1.16.5.jar:git-Purpur-969]
	at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:168) ~[patched_1.16.5.jar:git-Purpur-969]
	at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:540) ~[patched_1.16.5.jar:git-Purpur-969]
	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:150) ~[patched_1.16.5.jar:git-Purpur-969]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1461) ~[patched_1.16.5.jar:git-Purpur-969]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:387) ~[patched_1.16.5.jar:git-Purpur-969]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1284) ~[patched_1.16.5.jar:git-Purpur-969]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1010) ~[patched_1.16.5.jar:git-Purpur-969]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176) ~[patched_1.16.5.jar:git-Purpur-969]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
```

> What your java version?

java version 1.16.5, The problem persists in the latest 2.11.4 update @caoli5288

**Comment by caoli5288** [comment]
Seems spigot change the plugin classloader. I'll fix it soon.

**Comment by xPoyraz** [comment]
I noticed that in v2.11.5 this problem was gone but in v2.11.6 the error persists, I just wanted to inform. @caoli5288 

current error; 

`[11:01:41] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to PlayerSQL v2.11.6
java.lang.reflect.UndeclaredThrowableException: null
	at com.sun.proxy.$Proxy108.apply(Unknown Source) ~[?:?]
	at com.mengcraft.playersql.Utils.addChannel(Utils.java:47) ~[?:?]
	at com.mengcraft.playersql.EventExecutor.handle(EventExecutor.java:98) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor98.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1007]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:272) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.PlayerList.lambda$a$1(PlayerList.java:219) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:170) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:540) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:150) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1468) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:389) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1291) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1017) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.5.jar:git-Purpur-1007]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: com.sun.phobos.script.util.ExtendedScriptException: org.mozilla.javascript.EcmaError: TypeError: second argument to Function.prototype.apply must be an array
	at com.sun.phobos.script.javascript.RhinoScriptEngine.invokeMethod(RhinoScriptEngine.java:259) ~[patched_1.16.5.jar:git-Purpur-1007]
	at com.sun.phobos.script.util.InterfaceImplementor$InterfaceImplementorInvocationHandler.invoke(InterfaceImplementor.java:60) ~[patched_1.16.5.jar:git-Purpur-1007]
	... 19 more
Caused by: org.mozilla.javascript.EcmaError: TypeError: second argument to Function.prototype.apply must be an array
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3951) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3929) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3962) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.ScriptRuntime.typeError0(ScriptRuntime.java:3968) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.ScriptRuntime.getApplyArguments(ScriptRuntime.java:2596) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2574) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:287) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:101) ~[patched_1.16.5.jar:git-Purpur-1007]
	at com.sun.phobos.script.javascript.RhinoScriptEngine.invokeMethod(RhinoScriptEngine.java:245) ~[patched_1.16.5.jar:git-Purpur-1007]
	at com.sun.phobos.script.util.InterfaceImplementor$InterfaceImplementorInvocationHandler.invoke(InterfaceImplementor.java:60) ~[patched_1.16.5.jar:git-Purpur-1007]
	... 19 more`
