### ISSUE TITLE
PlayerSQL 2.11.6 error

### ISSUE THREAD

**Issue by xPoyraz** [caoli5288/PlayerSQL#68]
In v2.11.5 this problem was resolved but in v2.11.6 the error started again. @caoli5288 
thanks for your fast support 🙏

current error; 

```
`[11:01:41] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to PlayerSQL v2.11.6
java.lang.reflect.UndeclaredThrowableException: null
	at com.sun.proxy.$Proxy108.apply(Unknown Source) ~[?:?]
	at com.mengcraft.playersql.Utils.addChannel(Utils.java:47) ~[?:?]
	at com.mengcraft.playersql.EventExecutor.handle(EventExecutor.java:98) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor98.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1007]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:272) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.PlayerList.lambda$a$1(PlayerList.java:219) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:170) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:540) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:150) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1468) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:389) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1291) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1017) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.5.jar:git-Purpur-1007]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: com.sun.phobos.script.util.ExtendedScriptException: org.mozilla.javascript.EcmaError: TypeError: second argument to Function.prototype.apply must be an array
	at com.sun.phobos.script.javascript.RhinoScriptEngine.invokeMethod(RhinoScriptEngine.java:259) ~[patched_1.16.5.jar:git-Purpur-1007]
	at com.sun.phobos.script.util.InterfaceImplementor$InterfaceImplementorInvocationHandler.invoke(InterfaceImplementor.java:60) ~[patched_1.16.5.jar:git-Purpur-1007]
	... 19 more
Caused by: org.mozilla.javascript.EcmaError: TypeError: second argument to Function.prototype.apply must be an array
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3951) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3929) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3962) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.ScriptRuntime.typeError0(ScriptRuntime.java:3968) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.ScriptRuntime.getApplyArguments(ScriptRuntime.java:2596) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2574) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:287) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:101) ~[patched_1.16.5.jar:git-Purpur-1007]
	at com.sun.phobos.script.javascript.RhinoScriptEngine.invokeMethod(RhinoScriptEngine.java:245) ~[patched_1.16.5.jar:git-Purpur-1007]
	at com.sun.phobos.script.util.InterfaceImplementor$InterfaceImplementorInvocationHandler.invoke(InterfaceImplementor.java:60) ~[patched_1.16.5.jar:git-Purpur-1007]
	... 19 more`
```
```
[11:06:05] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to PlayerSQL v2.11.6
java.lang.reflect.UndeclaredThrowableException: null
	at com.sun.proxy.$Proxy107.apply(Unknown Source) ~[?:?]
	at com.mengcraft.playersql.Utils.getChannel(Utils.java:36) ~[?:?]
	at com.mengcraft.playersql.Utils.setAutoRead(Utils.java:40) ~[?:?]
	at com.mengcraft.playersql.UserManager.lockUser(UserManager.java:161) ~[?:?]
	at com.mengcraft.playersql.EventExecutor.handle(EventExecutor.java:156) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor97.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1007]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.PlayerList.disconnect(PlayerList.java:513) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1813) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:336) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:303) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.kickPlayer(CraftPlayer.java:494) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.craftersland.data.bridge.commands.handlers.SaveAndKickCmd.runCommand(SaveAndKickCmd.java:68) ~[?:?]
	at net.craftersland.data.bridge.events.ConsoleCommand.onCmd(ConsoleCommand.java:27) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor966.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1007]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:390) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1291) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1017) ~[patched_1.16.5.jar:git-Purpur-1007]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179) ~[patched_1.16.5.jar:git-Purpur-1007]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: com.sun.phobos.script.util.ExtendedScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "handle" from undefined (<Unknown source>#2) in <Unknown source> at line number 2
	at com.sun.phobos.script.javascript.RhinoScriptEngine.invokeMethod(RhinoScriptEngine.java:259) ~[patched_1.16.5.jar:git-Purpur-1007]
	at com.sun.phobos.script.util.InterfaceImplementor$InterfaceImplementorInvocationHandler.invoke(InterfaceImplementor.java:60) ~[patched_1.16.5.jar:git-Purpur-1007]
	... 28 more
Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "handle" from undefined (<Unknown source>#2)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3951) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3929) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3962) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3981) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.ScriptRuntime.undefReadError(ScriptRuntime.java:3993) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1505) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.gen._Unknown_source__34._c_apply_1(<Unknown source>:2) ~[?:?]
	at org.mozilla.javascript.gen._Unknown_source__34.call(<Unknown source>) ~[?:?]
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3282) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.gen._Unknown_source__34.call(<Unknown source>) ~[?:?]
	at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2586) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:287) ~[patched_1.16.5.jar:git-Purpur-1007]
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:101) ~[patched_1.16.5.jar:git-Purpur-1007]
	at com.sun.phobos.script.javascript.RhinoScriptEngine.invokeMethod(RhinoScriptEngine.java:245) ~[patched_1.16.5.jar:git-Purpur-1007]
	at com.sun.phobos.script.util.InterfaceImplementor$InterfaceImplementorInvocationHandler.invoke(InterfaceImplementor.java:60) ~[patched_1.16.5.jar:git-Purpur-1007]
	... 28 more

```

**Comment by caoli5288** [comment]
Seems some other plugins change then default javascript engine from nashorn to Rhino. It's not a generic issues related to playersql. :-/.
I'll fix it in an snapshot version.

**Comment by caoli5288** [comment]
https://jitpack.io/com/github/caoli5288/playersql/playersql/master-aade0d4c57-1/playersql-master-aade0d4c57-1.jar

**Comment by xPoyraz** [comment]
The error is gone! You are really fast, I have another problem. When I install playerSQL on Bungeecord, sync is broken, items are not registered, what can I do?  No errors in BungeeCord or spigot servers. @caoli5288

**Comment by caoli5288** [comment]
@xPoyraz I haven't maintained bungee side for a long time. Maybe you don't have to use it.

**Comment by xPoyraz** [comment]
> @xPoyraz I haven't maintained bungee side for a long time. Maybe you don't have to use it.

ok thanks for your quick support.
