### ISSUE TITLE
Could not load 'plugins/playersql.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by Bartflo20** [caoli5288/PlayerSQL#69]
Hello,

wanted to test youre plugin on a fresh spigot-1.16.5 installation, but as soon as I start the server, I get this error in the console:

`[Server thread/ERROR]: Could not load 'plugins/playersql.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/mengcraft/simpleorm/lib/Library
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.16.5.jar:3021-Spigot-bff5261-2ffdb31]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-1.16.5.jar:3021-Spigot-bff5261-2ffdb31]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-1.16.5.jar:3021-Spigot-bff5261-2ffdb31]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:382) ~[spigot-1.16.5.jar:3021-Spigot-bff5261-2ffdb31]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:185) ~[spigot-1.16.5.jar:3021-Spigot-bff5261-2ffdb31]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:811) ~[spigot-1.16.5.jar:3021-Spigot-bff5261-2ffdb31]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:166) ~[spigot-1.16.5.jar:3021-Spigot-bff5261-2ffdb31]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.NoClassDefFoundError: com/mengcraft/simpleorm/lib/Library
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_282]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_282]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.16.5.jar:3021-Spigot-bff5261-2ffdb31]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.16.5.jar:3021-Spigot-bff5261-2ffdb31]
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.mengcraft.simpleorm.lib.Library
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_282]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.16.5.jar:3021-Spigot-bff5261-2ffdb31]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.5.jar:3021-Spigot-bff5261-2ffdb31]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_282]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_282]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_282]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_282]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.16.5.jar:3021-Spigot-bff5261-2ffdb31]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.16.5.jar:3021-Spigot-bff5261-2ffdb31]
	... 7 more`

**Comment by caoli5288** [comment]
depend `simpleorm`.
https://github.com/caoli5288/SimpleORM

**Comment by Bartflo20** [comment]
Thanks for the fast respond.

I downloaded SimpleORM and put it in the plugins Folder:
![Screenshot 2021-03-16 123833](https://user-images.githubusercontent.com/80706061/111303306-a9424700-8654-11eb-9336-9fd277bf3008.png)

Sadly the error is still there.

**Comment by caoli5288** [comment]
please use the latest 1.4-SNAPSHOT version

**Comment by Bartflo20** [comment]
Oooof, thanks, that was a misstake on my side. Both plugins are running now.
Now I have to setup a SQL Server. Do I have to use mysql or should MariaDB also work?

**Comment by Bartflo20** [comment]
Soo... 8 hours later, I installed MariaDB and tired it...failed. Thought maybe only mysql works, installed mysql but I still get this errors:
`Error occurred while enabling PlayerSQL v2.11.6 (Is it up to date?)
com.mengcraft.simpleorm.DatabaseException: javax.persistence.PersistenceException: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:274) ~[?:?]
	at com.mengcraft.playersql.PluginMain.onEnable(PluginMain.java:91) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:493) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:407) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.reload(CraftServer.java:880) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at org.bukkit.Bukkit.reload(Bukkit.java:651) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:762) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:747) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:426) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:395) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1117) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:956) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: javax.persistence.PersistenceException: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.checkDataSource(DefaultServerFactory.java:482) ~[ebean-2.8.1.jar:?]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:170) ~[ebean-2.8.1.jar:?]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:63) ~[ebean-2.8.1.jar:?]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) ~[ebean-2.8.1.jar:?]
	at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:272) ~[?:?]
	... 18 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_282]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_282]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:403) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:335) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2187) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_282]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_282]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:403) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[?:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358) ~[?:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[?:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477) ~[?:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560) ~[?:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[?:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[?:?]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.checkDataSource(DefaultServerFactory.java:472) ~[ebean-2.8.1.jar:?]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:170) ~[ebean-2.8.1.jar:?]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:63) ~[ebean-2.8.1.jar:?]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) ~[ebean-2.8.1.jar:?]
	at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:272) ~[?:?]
	... 18 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_282]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_282]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_282]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_282]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_282]
	at java.net.Socket.connect(Socket.java:607) ~[?:1.8.0_282]
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:299) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2187) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_282]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_282]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:403) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323) ~[spigot-1.16.5.jar:3024-Spigot-79d53c2-90d6905]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[?:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358) ~[?:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[?:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477) ~[?:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560) ~[?:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[?:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[?:?]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.checkDataSource(DefaultServerFactory.java:472) ~[ebean-2.8.1.jar:?]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:170) ~[ebean-2.8.1.jar:?]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:63) ~[ebean-2.8.1.jar:?]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) ~[ebean-2.8.1.jar:?]
	at com.mengcraft.simpleorm.EbeanHandler.initialize(EbeanHandler.java:272) ~[?:?]
	... 18 more`
	
	Don't think thats a misstake on the plugin side, more on the sql server, but maybe you know what to do?

**Comment by Bartflo20** [comment]
So, SQL is online and everything is running so far. Thank you for your gread work!
