### ISSUE TITLE
关于1.16.5最新版与playerSQL

### ISSUE THREAD

**Issue by justicebearx** [caoli5288/PlayerSQL#70]
服务器核心：paper-1.16.5-732
JAVA版本：16.0.1
playerSQL版本：v2.11.6
simpleorm-1.4-SNAPSHOT

插件不能正常的加载报错如下：
[12:13:46 INFO]: [SimpleORM] Loading SimpleORM v1.4-SNAPSHOT
[12:13:46 ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @72ba2abe initializing SimpleORM v1.4-SNAPSHOT (Is it up to date?)
java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @72ba2abe
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
        at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
        at com.mengcraft.simpleorm.lib.Reflector.getRef(Reflector.java:45) ~[?:?]
        at com.mengcraft.simpleorm.lib.Reflector.lambda$getMethodRef$3(Reflector.java:64) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at com.mengcraft.simpleorm.lib.Reflector.getMethodRef(Reflector.java:64) ~[?:?]
        at com.mengcraft.simpleorm.lib.Reflector.getRef(Reflector.java:49) ~[?:?]
        at com.mengcraft.simpleorm.lib.Reflector.lambda$getMethodRef$3(Reflector.java:64) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at com.mengcraft.simpleorm.lib.Reflector.getMethodRef(Reflector.java:64) ~[?:?]
        at com.mengcraft.simpleorm.lib.Reflector.invoke(Reflector.java:83) ~[?:?]
        at com.mengcraft.simpleorm.lib.LibraryLoader.load(LibraryLoader.java:53) ~[?:?]
        at com.mengcraft.simpleorm.lib.LibraryLoader.load(LibraryLoader.java:43) ~[?:?]
        at com.mengcraft.simpleorm.ORM.loadExtLibrary(ORM.java:74) ~[?:?]
        at com.mengcraft.simpleorm.ORM.loadLibrary(ORM.java:68) ~[?:?]
        at com.mengcraft.simpleorm.ORM.onLoad(ORM.java:48) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:399) ~[patched_1.16.5.jar:git-Paper-732]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-732]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1068) ~[patched_1.16.5.jar:git-Paper-732]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-732]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[12:13:47 INFO]: [PlayerSQL] Loading PlayerSQL v2.11.6
[12:13:47 ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @72ba2abe initializing PlayerSQL v2.11.6 (Is it up to date?)
java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @72ba2abe
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
        at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
        at com.mengcraft.simpleorm.lib.Reflector.getRef(Reflector.java:45) ~[?:?]
        at com.mengcraft.simpleorm.lib.Reflector.lambda$getMethodRef$3(Reflector.java:64) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at com.mengcraft.simpleorm.lib.Reflector.getMethodRef(Reflector.java:64) ~[?:?]
        at com.mengcraft.simpleorm.lib.Reflector.getRef(Reflector.java:49) ~[?:?]
        at com.mengcraft.simpleorm.lib.Reflector.lambda$getMethodRef$3(Reflector.java:64) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at com.mengcraft.simpleorm.lib.Reflector.getMethodRef(Reflector.java:64) ~[?:?]
        at com.mengcraft.simpleorm.lib.Reflector.invoke(Reflector.java:83) ~[?:?]
        at com.mengcraft.simpleorm.lib.LibraryLoader.load(LibraryLoader.java:53) ~[?:?]
        at com.mengcraft.playersql.PluginMain.onLoad(PluginMain.java:53) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:399) ~[patched_1.16.5.jar:git-Paper-732]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-732]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1068) ~[patched_1.16.5.jar:git-Paper-732]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-732]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[12:13:49 INFO]: [SimpleORM] Enabling SimpleORM v1.4-SNAPSHOT*
[12:13:49 ERROR]: Error occurred while enabling SimpleORM v1.4-SNAPSHOT (Is it up to date?)
redis.clients.jedis.exceptions.InvalidURIException: Cannot open Redis connection due invalid URI.
        at redis.clients.jedis.JedisFactory.<init>(JedisFactory.java:80) ~[?:?]
        at redis.clients.jedis.JedisPool.<init>(JedisPool.java:282) ~[?:?]
        at redis.clients.jedis.JedisPool.<init>(JedisPool.java:276) ~[?:?]
        at redis.clients.jedis.JedisPool.<init>(JedisPool.java:265) ~[?:?]
        at redis.clients.jedis.JedisPool.<init>(JedisPool.java:254) ~[?:?]
        at com.mengcraft.simpleorm.redis.RedisProviders.of(RedisProviders.java:26) ~[?:?]
        at com.mengcraft.simpleorm.ORM.onEnable(ORM.java:86) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-732]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-732]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-732]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-732]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-732]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:270) ~[patched_1.16.5.jar:git-Paper-732]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1068) ~[patched_1.16.5.jar:git-Paper-732]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-732]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[12:13:49 INFO]: [SimpleORM] Disabling SimpleORM v1.4-SNAPSHOT
[12:13:55 INFO]: [SimpleORM] Enabling SimpleORM v1.4-SNAPSHOT*
[12:13:55 WARN]: Enabled plugin with unregistered PluginClassLoader SimpleORM v1.4-SNAPSHOT
[12:13:55 ERROR]: Error occurred while enabling SimpleORM v1.4-SNAPSHOT (Is it up to date?)
redis.clients.jedis.exceptions.InvalidURIException: Cannot open Redis connection due invalid URI.
        at redis.clients.jedis.JedisFactory.<init>(JedisFactory.java:80) ~[?:?]
        at redis.clients.jedis.JedisPool.<init>(JedisPool.java:282) ~[?:?]
        at redis.clients.jedis.JedisPool.<init>(JedisPool.java:276) ~[?:?]
        at redis.clients.jedis.JedisPool.<init>(JedisPool.java:265) ~[?:?]
        at redis.clients.jedis.JedisPool.<init>(JedisPool.java:254) ~[?:?]
        at com.mengcraft.simpleorm.redis.RedisProviders.of(RedisProviders.java:26) ~[?:?]
        at com.mengcraft.simpleorm.ORM.onEnable(ORM.java:86) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-732]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-732]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-732]
        at com.mengcraft.playersql.PluginMain.onEnable(PluginMain.java:81) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-732]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-732]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-732]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-732]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-732]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:593) ~[patched_1.16.5.jar:git-Paper-732]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-732]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1068) ~[patched_1.16.5.jar:git-Paper-732]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-732]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[12:13:55 INFO]: [SimpleORM] Disabling SimpleORM v1.4-SNAPSHOT
[12:13:55 ERROR]: Error occurred while enabling PlayerSQL v2.11.6 (Is it up to date?)
java.lang.NoClassDefFoundError: com/mengcraft/simpleorm/ORM
        at com.mengcraft.playersql.PluginMain.onEnable(PluginMain.java:84) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-732]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-732]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-732]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-732]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-732]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:593) ~[patched_1.16.5.jar:git-Paper-732]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-732]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1068) ~[patched_1.16.5.jar:git-Paper-732]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-732]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.mengcraft.simpleorm.ORM
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[patched_1.16.5.jar:git-Paper-732]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-732]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 11 more
[12:13:55 INFO]: [PlayerSQL] Disabling PlayerSQL v2.11.6

**Comment by justicebearx** [comment]
我找到原因了.. 换成了JAVA8顺利加载了
谢谢梦梦还在更新这个插件
有时间兼容下JAVA16吧

**Comment by caoli5288** [comment]
这个是模块化加载的问题，你在java启动参数里允许匿名模块访问就可以啦。因为大部分国内服务器还是在java8所以不太可能去主动兼容模块化的东西。

**Comment by justicebearx** [comment]
--illegal-access="permit" 我加了这个参数但是不行 请问是应该填哪个参数？

**Comment by caoli5288** [comment]
`--add-opens java.base/java.net=ALL-UNNAMED`
大概是这个

**Comment by justicebearx** [comment]
谢谢了 可是试了一下不起作用
