### ISSUE TITLE
I can't use command

### ISSUE THREAD

**Issue by YTiceice** [caoli5288/PlayerSQL#75]
playersql                                                                     
[13:13:18 INFO]: /playersql open inventory                                      
[13:13:18 INFO]: /playersql open chest                                          
[13:13:18 INFO]: /playersql config                                              
[13:13:18 INFO]: /playersql open                                                
> playersql config                                                              
[13:13:22 WARN]: Unexpected exception while parsing console command "playersql c
onfig"                                                                          
org.bukkit.command.CommandException: Unhandled exception executing command 'play
ersql' in plugin PlayerSQL v2.12.2                                              
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[pat
ched_1.17.1.jar:git-Paper-325]                                                  
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:15
9) ~[patched_1.17.1.jar:git-Paper-325]                                          
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServ
er.java:852) ~[patched_1.17.1.jar:git-Paper-325]                                
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(Cra
ftServer.java:815) ~[patched_1.17.1.jar:git-Paper-325]                          
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(De
dicatedServer.java:529) ~[patched_1.17.1.jar:git-Paper-325]                     
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(Dedicated
Server.java:491) ~[patched_1.17.1.jar:git-Paper-325]                            
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:
1475) ~[patched_1.17.1.jar:git-Paper-325]                                       
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1
274) ~[patched_1.17.1.jar:git-Paper-325]                                        
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.ja
va:319) ~[patched_1.17.1.jar:git-Paper-325]                                     
        at java.lang.Thread.run(Thread.java:831) ~[?:?]                         
Caused by: java.util.NoSuchElementException                                     
        at java.util.Arrays$ArrayItr.next(Arrays.java:4244) ~[?:?]              
        at com.mengcraft.playersql.Commands.config(Commands.java:33) ~[playersql
.jar:?]                                                                         
        at com.mengcraft.playersql.lib.BiRegistry.handle(BiRegistry.java:26) ~[p
layersql.jar:?]                                                                 
        at com.mengcraft.playersql.Commands.onCommand(Commands.java:154) ~[playe
rsql.jar:?]                                                                     
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[pat
ched_1.17.1.jar:git-Paper-325]                                                  
        ... 9 more

**Comment by caoli5288** [comment]
What do you want to do? This command is used for debug, not for players.

**Comment by YTiceice** [comment]
ok
