### ISSUE TITLE
关于后台疯狂报错

### ISSUE THREAD

**Issue by jiongjionger** [caoli5288/PlayerSQL#9]
由于最新的版本导致玩家无法进入游戏，使用了倒数第二个构建版本
今天发现有不少玩家说自己无法进入游戏，提示data lock，于是查看后台，发现后台错误刷屏，多达100W行，类似这样：
[05:16:08] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:08] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:08] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:08] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:08] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:08] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:08] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:08] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:08] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:08] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:08] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:08] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:08] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:08] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:08] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:09] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:09] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:09] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:09] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:09] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:09] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:09] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:09] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:09] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:09] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:09] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:09] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception
java.lang.NullPointerException
[05:16:09] [Server thread/WARN]: [PlayerSQL] Task #26 for PlayerSQL v1.10.3 generated an exception

**Comment by jiongjionger** [comment]
定位发现是这行代码出错：
UUID key = p.getUniqueId();

**Comment by Cnly** [comment]
能提供一下具体构建版本号以及出错代码准确位置吗？

**Comment by caoli5288** [comment]
提供下准确的出错位置

**Comment by jiongjionger** [comment]
构建版本号是：#30，然而#29也会出现这个问题
具体报错：
java.lang.NullPointerException
	at com.mengcraft.playersql.SyncManager.load(SyncManager.java:63) ~[?:?]
	at com.mengcraft.playersql.task.TimerCheckTask.normal(TimerCheckTask.java:64) ~[?:?]
	at com.mengcraft.playersql.task.TimerCheckTask.run(TimerCheckTask.java:46) ~[?:?]

具体报错方法：
public void load(final Player p, String value) {
        UUID key = p.getUniqueId();
        if (p.isOnline()) {
            JsonArray array = parser.parse(value).getAsJsonArray();
            load(p, array);
            compond.unlock(key);
            compond.map().remove(key);
        } else {
            /*
             * Player is null(may be impossible) or offline here
             * but the player's data on the database has been locked. Perform an unlock task.
             * This is an infrequent case.
             */
            service.execute(new UnlockTask(key));
        }
    }
其中的UUID key = p.getUniqueId();报错
我的临时解决方法是在前面加上
if(p == null || p.getUniqueId() == null){
    return;
}
我比较担心是否这么做有概率导致玩家背包没有正常加载/同步

**Comment by caoli5288** [comment]
这是登录的瞬间秒掉线的情况，你是不是有很多插件干涉登录过程。

**Comment by jiongjionger** [comment]
干涉登录过程的插件有：
1. nocheatplus
2. neverlag（我自己写的那个，防止小号登录压测的）
3. fastlogin（依然我写的一个登录插件）
关键是如果因为其他插件被踢出日志会有显示。而且网络质量不好的情况下客户端秒掉线或者客户端崩溃这类的也应该考虑进去呀

**Comment by caoli5288** [comment]
有考虑的，数据锁的有效期是5分钟。你试试最新构筑吧（顺便建议你做的登录插件不要允许挤人，这会很烦的

**Comment by jiongjionger** [comment]
并没有允许挤人。我试试最新的版本。

**Comment by jiongjionger** [comment]
另外在代码内没有发现『数据锁的有效期是5分钟』的功能代码，能否告知下具体位置？

**Comment by caoli5288** [comment]
一行很小的代码，看不到也很正常。
com.mengcraft.playersql.task.LoadTask#run()
line 62
我测试的时候也没有发现报错，这个issue先关闭，有问题在另一个issue一起说。

**Comment by Cnly** [comment]
这个问题应该已经在https://github.com/caoli5288/PlayerSQL/commit/7655b40d62e2f920fc03d1100fc3a5ce0c2d27cf中解决。
